GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/64b8302a7900557e8c64a64a

###

GET http://localhost:5000/api/users/role/admin

###

GET http://localhost:5000/api/users/count/admin

###

GET http://localhost:5000/api/users/count/all

###

POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "username": "test123",
    "email": "test23@yahoo.com",
    "password": "happyhappyhappy",
    "role": "ADMIN"
}


###
PUT http://localhost:5000/api/courses/65225902a20fb6355e4d63d9 HTTP/1.1
Content-Type: 'application/json',
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV2YWx1YXRvciIsImVtYWlsIjoiZXZhbHVhdG9yQGhvdG1haWwuY29tIiwicm9sZSI6IkVWQUxVQVRPUiIsImlhdCI6MTY5Njk5Nzc0MSwiZXhwIjoxNjk3MDAxMzQxfQ.hjsXfHbf0XGgJJ8lJUhekNXZthqSuqNEM2htSTz-xL8'
# {
#     "status":"Approved"
# }