GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/64b8302a7900557e8c64a64a

###

GET http://localhost:5000/api/users/role/admin

###

GET http://localhost:5000/api/users/count/admin

###

GET http://localhost:5000/api/users/count/all

###

POST http://localhost:5000/api/users HTTP/1.1
content-type: application/json

{
    "username": "test123",
    "email": "test23@yahoo.com",
    "password": "happyhappyhappy",
    "role": "ADMIN"
}

###

GET http://localhost:5000/api/subjects
Content-Type: 'application/json',
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbnR5YSIsImVtYWlsIjoiY2hvY2hpQGdtYWlsLmNvbSIsInJvbGUiOiJDT05UUklCVVRPUiIsImlhdCI6MTY5MzY1MzIxMSwiZXhwIjoxNjkzNjU2ODExfQ.qVGqW5QPZrkUQGW_s2vzrUbpCztP4aK5qf431zjVcSc'

###
GET http://localhost:5000/api/subjects/deptEnum
Content-Type: 'application/json',
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWtoYXIiLCJlbWFpbCI6InByYWtoYXJAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjk0MjkwNTg3LCJleHAiOjE2OTQyOTQxODd9.3ExlscgFHI0B7m7eVgqVAMrgdTCFYLwg_WjPdeiXrKE'
###
GET http://localhost:5000/api/subjects/yearEnum
Content-Type: 'application/json',
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWtoYXIiLCJlbWFpbCI6InByYWtoYXJAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjk0MjkwNTg3LCJleHAiOjE2OTQyOTQxODd9.3ExlscgFHI0B7m7eVgqVAMrgdTCFYLwg_WjPdeiXrKE'

###
GET http://localhost:5000/api/subjects/semList
Content-Type: 'application/json',
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWtoYXIiLCJlbWFpbCI6InByYWtoYXJAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjk0MjkwNTg3LCJleHAiOjE2OTQyOTQxODd9.3ExlscgFHI0B7m7eVgqVAMrgdTCFYLwg_WjPdeiXrKE'
